### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by prakharchoudhary** [prakharchoudhary/TodoListMaker#2]

**Comment by aman-roy** [comment]
Can I fix it's UI?

**Comment by prakharchoudhary** [comment]
yes please go ahead!

**Comment by prakharchoudhary** [comment]
Hi @aman-roy, any updates on the issue?

**Comment by aman-roy** [comment]
Sorry for the delay due to my exams. I'll surely do it by tomorrow.

**Comment by aman-roy** [comment]
![screenshot from 2017-10-14 17-50-31](https://user-images.githubusercontent.com/13317901/31575607-4839f96e-b108-11e7-97bd-43a51d3c1600.png)

@prakharchoudhary Almost finished. How is it looking?

**Comment by prakharchoudhary** [comment]
@aman-roy Looks nice! I am excited to see the finished UI.

**Comment by aman-roy** [comment]
See the pull request. I am unable to fix the check-uncheck button. Except that everything is working awesome.

**Comment by aman-roy** [comment]
Done with the priority box.

**Comment by prakharchoudhary** [comment]
closed by #18
